name: Abyss Lounge website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build project
      run: npm run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v4
      with:
        path: ./dist
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4